// <auto-generated />
namespace DotNetSpain.StreamAnalytics.PersistenceStorageRole.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-beta1-40122")]
    public sealed partial class Path : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Path));
        
        string IMigrationMetadata.Id
        {
            get { return "201502251625256_Path"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
